name: pranacobol_monorepo
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - packages/pranacobol_client
  - packages/pranacobol_server
  - packages/pranacobol_flutter

dev_dependencies:
  melos: ^6.0.0
